basePath: /api/v1
definitions:
  column.Column:
    properties:
      author:
        type: string
      avatar:
        $ref: '#/definitions/column.Image'
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
  column.Image:
    properties:
      id:
        type: string
      url:
        type: string
    type: object
  image.Image:
    properties:
      createdAt:
        type: string
      id:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
  post.Image:
    properties:
      id:
        type: string
      url:
        type: string
    type: object
  post.Post:
    properties:
      author:
        $ref: '#/definitions/user.User'
      columnId:
        type: string
      content:
        type: string
      createdAt:
        type: string
      excerpt:
        type: string
      id:
        type: string
      image:
        $ref: '#/definitions/post.Image'
      title:
        type: string
      updatedAt:
        type: string
    type: object
  requests.ColumnRequest:
    properties:
      avatarId:
        type: string
      description:
        type: string
      title:
        type: string
    type: object
  requests.LoginByEmailRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  requests.PostRequest:
    properties:
      authorId:
        type: string
      columnId:
        type: string
      content:
        type: string
      image:
        type: string
      title:
        type: string
    type: object
  requests.SignupUsingEmailRequest:
    properties:
      email:
        type: string
      nickName:
        type: string
      password:
        type: string
      password_confirm:
        type: string
    type: object
  requests.UserUpdateProfileRequest:
    properties:
      avatarId:
        type: string
      description:
        type: string
      nickName:
        type: string
    type: object
  user.Image:
    properties:
      id:
        type: string
      url:
        type: string
    type: object
  user.User:
    properties:
      avatar:
        $ref: '#/definitions/user.Image'
      columnId:
        type: string
      createdAt:
        type: string
      description:
        type: string
      email:
        type: string
      id:
        type: string
      nickName:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: 875151567@qq.com
    name: AA12
    url: https://qm.qq.com/cgi-bin/qm/qr?k=qjar90G1gAtMF6uR7-8WLk5OvpD7sjUj&noverify=0
  description: GDColumn是一个基于 Gin 框架搭建的防知乎专栏后端 API。
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GDColumn
  version: "1.0"
paths:
  /auth/login/using-email:
    post:
      consumes:
      - application/json
      description: 需要用户名密码
      parameters:
      - description: 用户登录，需要提供用户的邮箱和密码
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.LoginByEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token":token}
          schema:
            type: json
      summary: 发送请求用户登录
      tags:
      - user 关于用户的路由，登录，注册，获取当前用户等等
  /auth/signup/using-email:
    post:
      consumes:
      - application/json
      description: 需要用户名密码
      parameters:
      - description: 用户注册，需要提供用户的邮箱和密码
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.SignupUsingEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: 注册用户
      tags:
      - user 关于用户的路由，登录，注册，获取当前用户等等
  /columns:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: order
        type: string
      - in: query
        name: perPage
        type: string
      - in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/column.Column'
      summary: 发送请求，获得专栏列表
      tags:
      - column 关于专栏的一些操作信息
  /columns/:
    put:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 待更新专栏数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.ColumnRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/column.Column'
      summary: 发送请求，更新个人专栏信息
      tags:
      - column 关于专栏的一些操作信息
  /columns/{id}:
    get:
      parameters:
      - description: 专栏ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/column.Column'
      summary: 发送请求，获取一个专栏详情
      tags:
      - column 关于专栏的一些操作信息
  /columns/{id}/posts:
    get:
      description: 专栏ID
      parameters:
      - description: 专栏ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/post.Post'
      summary: 发送请求获取属于专栏的文章信息
      tags:
      - post 关于文章的一些操作信息
  /current:
    get:
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: 获取当前用户信息
      tags:
      - user 关于用户的路由，登录，注册，获取当前用户等等
  /posts:
    post:
      consumes:
      - application/json
      description: 需要标题、内容
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 新建文章，需要提供标题和内容
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/post.Post'
      summary: 新建文章
      tags:
      - post 关于文章的一些操作信息
  /posts/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/post.Post'
      summary: 发送请求，删除单个文章
      tags:
      - post 关于文章的一些操作信息
    get:
      description: 文章ID
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/post.Post'
      summary: 发送请求获取单个文章信息
      tags:
      - post 关于文章的一些操作信息
    put:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: 待更新文章数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/post.Post'
      summary: 发送请求，更新单个文章信息
      tags:
      - post 关于文章的一些操作信息
  /upload:
    post:
      description: 专栏ID
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/image.Image'
      summary: 上传文件
      tags:
      - file 关于文件上传的一些操作信息
  /users:
    put:
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 待更新用户数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.UserUpdateProfileRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: 更新当前用户信息
      tags:
      - user 关于用户的路由，登录，注册，获取当前用户等等
swagger: "2.0"
